# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2coffee', '0002_coffeepotevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeepotevent',
            name='type',
            field=models.CharField(choices=[('brew_started', 'brewing started'), ('brew_finished', 'brewing finished')], max_length=254),
        ),
        migrations.AlterField(
            model_name='sensorevent',
            name='name',
            field=models.CharField(choices=[('power-switch', 'Power switched'), ('power-meter', 'Power metered'), ('power-meter-has-changed', 'Power meter changed')], max_length=254),
        ),
    ]
